export const EVENTS = {
  HEARTBEAT: "HEARTBEAT",
  PLATFORM_CONNECTED: "PLATFORM_CONNECTED",

  PROBLEM_PAGE_OPENED: "PROBLEM_PAGE_OPENED",
  SESSION_ENDED: "SESSION_ENDED",
  SUBMISSION_RESULT: "SUBMISSION_RESULT"
} as const;